general:
  me: train_cfg.yml
  output: local
  run_name: test
  save_pdb: true
  batch_save_freq: 2
  epoch_save_freq: 5
data:
  path: data/
  idpseq:
  - example_data
  train_size: 
  - 0.5
  val_size: 
  - 0.1
  tr_batch_size: 16
  val_batch_size: 64
  test_batch_size: 64
training:
  lr_scheduler:
    max_lr: 0.001
    warmup_no_steps: 1000
    start_decay_after_n_steps: 5000
    decay_every_n_steps: 5000
  ema_decay: 0.99
  trainer:
    gradient_clip_val: 0.2
    accumulate_grad_batches: 4
    accelerator: gpu
    devices: 2
    max_epochs: 100
    num_sanity_val_steps: 0
  diff_pkl: data/diff_igso3.pkl
  loss:
    weights:
      fape: 1
      dist: 0.01
      angular: 0.1
      violation: 0
    fape:
      use_clamp: 0.5
      clamp_distance: 10
    dist:
      loop_clamp: 10
      sidechain: 0
      sidechain_clamp: 8
diffuse:
  n_tsteps: 200
  n_tsteps_inf: 40
model:
  t_embed_dim: 32
  t2d_params:
    DMIN: 3.0
    DMAX: 39.0
    DBINS: 32
    ABINS: 32
  self_condition: true
  trunk:
    num_blocks: 2
    sequence_state_dim: 128
    pairwise_state_dim: 64
    sequence_head_width: 32
    pairwise_head_width: 32
    max_recycles: 3
    recycle_min_bin: 3.375
    recycle_max_bin: 39.375
    structure_module:
      c_s: 256
      c_z: 64
      c_ipa: 16
      c_resnet: 128
      no_heads_ipa: 8
      no_qk_points: 4
      no_v_points: 8
      dropout_rate: 0.1
      no_blocks: 4
      no_transition_layers: 1
      no_resnet_blocks: 2
      no_angles: 7
      trans_scale_factor: 10
